---
version: '3.9'

name: tmux-pane-focus-plugin

services:
  tmux:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .tmux.conf:/home/developer/.tmux.conf
    - .:/home/developer/.tmux/plugins/tmux-pane-focus

  tests:
    image: shellspec/shellspec-debian:0.28.1
    volumes:
    - .:/src
    command: ["-s", "bash"]
