---
name: Bash Dev

on:
  push:
    branches: ['**', '!main']
    paths-ignore:
    - .github/dependabot.yml
    - '*.md'
    - '*.yaml'
    - .gitignore
    - LICENSE

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile

    - name: ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0

  unittests:
    needs: linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install kcov
      run: |
        sudo apt-get update
        sudo apt-get install -y bash git kcov

    - name: Install Shellspec
      run: |
        cd /opt/
        sudo git clone https://github.com/shellspec/shellspec.git
        sudo ln -s /opt/shellspec/shellspec /usr/local/bin/shellspec

    - name: Run shellspec with kcov
      env:
        SHELLSPEC_KCOV_OPTS: "--include-pattern=*.sh"
      run: |
        shellspec -s bash --kcov
