---
name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Generate release notes
      run: |
        gh release create ${{github.ref_name}} --generate-notes --latest --notes "[Changelog](./CHANGELOG.md), [Documentation](./docs)"
